version: "3.11.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend/
    command: uvicorn hirey.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./hirey/.env
    ports:
      - 8000:8000
